//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketingService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MarketingService.NMIRSoap")]
    public interface NMIRSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        System.Threading.Tasks.Task<MarketingService.RegisterResponse> RegisterAsync(MarketingService.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Revoke", ReplyAction="*")]
        System.Threading.Tasks.Task<MarketingService.RevokeResponse> RevokeAsync(MarketingService.RevokeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReActive", ReplyAction="*")]
        System.Threading.Tasks.Task<MarketingService.ReActiveResponse> ReActiveAsync(MarketingService.ReActiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPersonStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<MarketingService.GetPersonStatusResponse> GetPersonStatusAsync(MarketingService.GetPersonStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPersonCode", ReplyAction="*")]
        System.Threading.Tasks.Task<MarketingService.GetPersonCodeResponse> GetPersonCodeAsync(MarketingService.GetPersonCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPersonCompany", ReplyAction="*")]
        System.Threading.Tasks.Task<MarketingService.GetPersonCompanyResponse> GetPersonCompanyAsync(MarketingService.GetPersonCompanyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register", Namespace="http://tempuri.org/", Order=0)]
        public MarketingService.RegisterRequestBody Body;
        
        public RegisterRequest()
        {
        }
        
        public RegisterRequest(MarketingService.RegisterRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nationalCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string fatherName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string phone1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string phone2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string birthDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string idNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string education;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string postalCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string parentNationalCode;
        
        public RegisterRequestBody()
        {
        }
        
        public RegisterRequestBody(string username, string password, string nationalCode, string firstName, string lastName, string fatherName, string phone1, string phone2, string email, string birthDate, string idNo, string education, string address, string postalCode, string parentNationalCode)
        {
            this.username = username;
            this.password = password;
            this.nationalCode = nationalCode;
            this.firstName = firstName;
            this.lastName = lastName;
            this.fatherName = fatherName;
            this.phone1 = phone1;
            this.phone2 = phone2;
            this.email = email;
            this.birthDate = birthDate;
            this.idNo = idNo;
            this.education = education;
            this.address = address;
            this.postalCode = postalCode;
            this.parentNationalCode = parentNationalCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public MarketingService.RegisterResponseBody Body;
        
        public RegisterResponse()
        {
        }
        
        public RegisterResponse(MarketingService.RegisterResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegisterResult;
        
        public RegisterResponseBody()
        {
        }
        
        public RegisterResponseBody(string RegisterResult)
        {
            this.RegisterResult = RegisterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RevokeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Revoke", Namespace="http://tempuri.org/", Order=0)]
        public MarketingService.RevokeRequestBody Body;
        
        public RevokeRequest()
        {
        }
        
        public RevokeRequest(MarketingService.RevokeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RevokeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nationalCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool IsCompanyRequest;
        
        public RevokeRequestBody()
        {
        }
        
        public RevokeRequestBody(string username, string password, string nationalCode, bool IsCompanyRequest)
        {
            this.username = username;
            this.password = password;
            this.nationalCode = nationalCode;
            this.IsCompanyRequest = IsCompanyRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RevokeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RevokeResponse", Namespace="http://tempuri.org/", Order=0)]
        public MarketingService.RevokeResponseBody Body;
        
        public RevokeResponse()
        {
        }
        
        public RevokeResponse(MarketingService.RevokeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RevokeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RevokeResult;
        
        public RevokeResponseBody()
        {
        }
        
        public RevokeResponseBody(string RevokeResult)
        {
            this.RevokeResult = RevokeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReActiveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReActive", Namespace="http://tempuri.org/", Order=0)]
        public MarketingService.ReActiveRequestBody Body;
        
        public ReActiveRequest()
        {
        }
        
        public ReActiveRequest(MarketingService.ReActiveRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReActiveRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nationalCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool IsCompanyRequest;
        
        public ReActiveRequestBody()
        {
        }
        
        public ReActiveRequestBody(string username, string password, string nationalCode, bool IsCompanyRequest)
        {
            this.username = username;
            this.password = password;
            this.nationalCode = nationalCode;
            this.IsCompanyRequest = IsCompanyRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReActiveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReActiveResponse", Namespace="http://tempuri.org/", Order=0)]
        public MarketingService.ReActiveResponseBody Body;
        
        public ReActiveResponse()
        {
        }
        
        public ReActiveResponse(MarketingService.ReActiveResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReActiveResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReActiveResult;
        
        public ReActiveResponseBody()
        {
        }
        
        public ReActiveResponseBody(string ReActiveResult)
        {
            this.ReActiveResult = ReActiveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonStatus", Namespace="http://tempuri.org/", Order=0)]
        public MarketingService.GetPersonStatusRequestBody Body;
        
        public GetPersonStatusRequest()
        {
        }
        
        public GetPersonStatusRequest(MarketingService.GetPersonStatusRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPersonStatusRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nationalCode;
        
        public GetPersonStatusRequestBody()
        {
        }
        
        public GetPersonStatusRequestBody(string username, string password, string nationalCode)
        {
            this.username = username;
            this.password = password;
            this.nationalCode = nationalCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public MarketingService.GetPersonStatusResponseBody Body;
        
        public GetPersonStatusResponse()
        {
        }
        
        public GetPersonStatusResponse(MarketingService.GetPersonStatusResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPersonStatusResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPersonStatusResult;
        
        public GetPersonStatusResponseBody()
        {
        }
        
        public GetPersonStatusResponseBody(string GetPersonStatusResult)
        {
            this.GetPersonStatusResult = GetPersonStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonCode", Namespace="http://tempuri.org/", Order=0)]
        public MarketingService.GetPersonCodeRequestBody Body;
        
        public GetPersonCodeRequest()
        {
        }
        
        public GetPersonCodeRequest(MarketingService.GetPersonCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPersonCodeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nationalCode;
        
        public GetPersonCodeRequestBody()
        {
        }
        
        public GetPersonCodeRequestBody(string username, string password, string nationalCode)
        {
            this.username = username;
            this.password = password;
            this.nationalCode = nationalCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public MarketingService.GetPersonCodeResponseBody Body;
        
        public GetPersonCodeResponse()
        {
        }
        
        public GetPersonCodeResponse(MarketingService.GetPersonCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPersonCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPersonCodeResult;
        
        public GetPersonCodeResponseBody()
        {
        }
        
        public GetPersonCodeResponseBody(string GetPersonCodeResult)
        {
            this.GetPersonCodeResult = GetPersonCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonCompanyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonCompany", Namespace="http://tempuri.org/", Order=0)]
        public MarketingService.GetPersonCompanyRequestBody Body;
        
        public GetPersonCompanyRequest()
        {
        }
        
        public GetPersonCompanyRequest(MarketingService.GetPersonCompanyRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPersonCompanyRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nationalCode;
        
        public GetPersonCompanyRequestBody()
        {
        }
        
        public GetPersonCompanyRequestBody(string username, string password, string nationalCode)
        {
            this.username = username;
            this.password = password;
            this.nationalCode = nationalCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonCompanyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonCompanyResponse", Namespace="http://tempuri.org/", Order=0)]
        public MarketingService.GetPersonCompanyResponseBody Body;
        
        public GetPersonCompanyResponse()
        {
        }
        
        public GetPersonCompanyResponse(MarketingService.GetPersonCompanyResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPersonCompanyResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPersonCompanyResult;
        
        public GetPersonCompanyResponseBody()
        {
        }
        
        public GetPersonCompanyResponseBody(string GetPersonCompanyResult)
        {
            this.GetPersonCompanyResult = GetPersonCompanyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface NMIRSoapChannel : MarketingService.NMIRSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class NMIRSoapClient : System.ServiceModel.ClientBase<MarketingService.NMIRSoap>, MarketingService.NMIRSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NMIRSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(NMIRSoapClient.GetBindingForEndpoint(endpointConfiguration), NMIRSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NMIRSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NMIRSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NMIRSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NMIRSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NMIRSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MarketingService.RegisterResponse> MarketingService.NMIRSoap.RegisterAsync(MarketingService.RegisterRequest request)
        {
            return base.Channel.RegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<MarketingService.RegisterResponse> RegisterAsync(string username, string password, string nationalCode, string firstName, string lastName, string fatherName, string phone1, string phone2, string email, string birthDate, string idNo, string education, string address, string postalCode, string parentNationalCode)
        {
            MarketingService.RegisterRequest inValue = new MarketingService.RegisterRequest();
            inValue.Body = new MarketingService.RegisterRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.nationalCode = nationalCode;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.fatherName = fatherName;
            inValue.Body.phone1 = phone1;
            inValue.Body.phone2 = phone2;
            inValue.Body.email = email;
            inValue.Body.birthDate = birthDate;
            inValue.Body.idNo = idNo;
            inValue.Body.education = education;
            inValue.Body.address = address;
            inValue.Body.postalCode = postalCode;
            inValue.Body.parentNationalCode = parentNationalCode;
            return ((MarketingService.NMIRSoap)(this)).RegisterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MarketingService.RevokeResponse> MarketingService.NMIRSoap.RevokeAsync(MarketingService.RevokeRequest request)
        {
            return base.Channel.RevokeAsync(request);
        }
        
        public System.Threading.Tasks.Task<MarketingService.RevokeResponse> RevokeAsync(string username, string password, string nationalCode, bool IsCompanyRequest)
        {
            MarketingService.RevokeRequest inValue = new MarketingService.RevokeRequest();
            inValue.Body = new MarketingService.RevokeRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.nationalCode = nationalCode;
            inValue.Body.IsCompanyRequest = IsCompanyRequest;
            return ((MarketingService.NMIRSoap)(this)).RevokeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MarketingService.ReActiveResponse> MarketingService.NMIRSoap.ReActiveAsync(MarketingService.ReActiveRequest request)
        {
            return base.Channel.ReActiveAsync(request);
        }
        
        public System.Threading.Tasks.Task<MarketingService.ReActiveResponse> ReActiveAsync(string username, string password, string nationalCode, bool IsCompanyRequest)
        {
            MarketingService.ReActiveRequest inValue = new MarketingService.ReActiveRequest();
            inValue.Body = new MarketingService.ReActiveRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.nationalCode = nationalCode;
            inValue.Body.IsCompanyRequest = IsCompanyRequest;
            return ((MarketingService.NMIRSoap)(this)).ReActiveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MarketingService.GetPersonStatusResponse> MarketingService.NMIRSoap.GetPersonStatusAsync(MarketingService.GetPersonStatusRequest request)
        {
            return base.Channel.GetPersonStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<MarketingService.GetPersonStatusResponse> GetPersonStatusAsync(string username, string password, string nationalCode)
        {
            MarketingService.GetPersonStatusRequest inValue = new MarketingService.GetPersonStatusRequest();
            inValue.Body = new MarketingService.GetPersonStatusRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.nationalCode = nationalCode;
            return ((MarketingService.NMIRSoap)(this)).GetPersonStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MarketingService.GetPersonCodeResponse> MarketingService.NMIRSoap.GetPersonCodeAsync(MarketingService.GetPersonCodeRequest request)
        {
            return base.Channel.GetPersonCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<MarketingService.GetPersonCodeResponse> GetPersonCodeAsync(string username, string password, string nationalCode)
        {
            MarketingService.GetPersonCodeRequest inValue = new MarketingService.GetPersonCodeRequest();
            inValue.Body = new MarketingService.GetPersonCodeRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.nationalCode = nationalCode;
            return ((MarketingService.NMIRSoap)(this)).GetPersonCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MarketingService.GetPersonCompanyResponse> MarketingService.NMIRSoap.GetPersonCompanyAsync(MarketingService.GetPersonCompanyRequest request)
        {
            return base.Channel.GetPersonCompanyAsync(request);
        }
        
        public System.Threading.Tasks.Task<MarketingService.GetPersonCompanyResponse> GetPersonCompanyAsync(string username, string password, string nationalCode)
        {
            MarketingService.GetPersonCompanyRequest inValue = new MarketingService.GetPersonCompanyRequest();
            inValue.Body = new MarketingService.GetPersonCompanyRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.nationalCode = nationalCode;
            return ((MarketingService.NMIRSoap)(this)).GetPersonCompanyAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NMIRSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.NMIRSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NMIRSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://unicode.mimt.gov.ir/nmir.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.NMIRSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://unicode.mimt.gov.ir/nmir.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            NMIRSoap,
            
            NMIRSoap12,
        }
    }
}
